// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa3Y_xvuyfoRtORoGDNweZeap9ZaGHB0E',
    appId: '1:744280216992:web:41903814c1c53f400f40c5',
    messagingSenderId: '744280216992',
    projectId: 'fyp-animalcare',
    authDomain: 'fyp-animalcare.firebaseapp.com',
    storageBucket: 'fyp-animalcare.appspot.com',
    measurementId: 'G-KWEMWMBZGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Kn025auj9KzNpebEkCttoSdiNuo9nXo',
    appId: '1:744280216992:android:dc5e4de948ae90b60f40c5',
    messagingSenderId: '744280216992',
    projectId: 'fyp-animalcare',
    storageBucket: 'fyp-animalcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMKUgkn7nZArC8HYGxL10jhVza9LKE5Tc',
    appId: '1:744280216992:ios:276b7b017030feef0f40c5',
    messagingSenderId: '744280216992',
    projectId: 'fyp-animalcare',
    storageBucket: 'fyp-animalcare.appspot.com',
    iosBundleId: 'com.example.fypAnimalcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMKUgkn7nZArC8HYGxL10jhVza9LKE5Tc',
    appId: '1:744280216992:ios:276b7b017030feef0f40c5',
    messagingSenderId: '744280216992',
    projectId: 'fyp-animalcare',
    storageBucket: 'fyp-animalcare.appspot.com',
    iosBundleId: 'com.example.fypAnimalcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa3Y_xvuyfoRtORoGDNweZeap9ZaGHB0E',
    appId: '1:744280216992:web:f06b8097cb0cf74d0f40c5',
    messagingSenderId: '744280216992',
    projectId: 'fyp-animalcare',
    authDomain: 'fyp-animalcare.firebaseapp.com',
    storageBucket: 'fyp-animalcare.appspot.com',
    measurementId: 'G-FRP4L51KBS',
  );

}